sonar.host.url=http://sonarqube.jio.com:9000/
sonar.java.binaries=.
sonar.sources=.
sonar.branch.name=master
sonar.branch.longLivedBranches.regex=master
sonar.exclusions=src/assets/**,src/environments/**
sonar.projectKey=Auto-Pipeline-Scripts
sonar.projectName=Auto-Pipeline-Scripts
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
